name: Deno lint

on:
  pull_request:
    branches:
      - main
  push:
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1

      - name: Run lint
        run: deno task lint
